#!/bin/bash

export PYTHONPATH=$SPARK_HOME/python:$(echo $SPARK_HOME/python/lib/py4j-*-src.zip)

export PYSPARK_PYTHON=/opt/conda/bin/python

if [[ "x$JUPYTER_NOTEBOOK_PASSWORD" != "x" ]]; then
    HASH=$(python -c "from notebook.auth import passwd; print(passwd('$JUPYTER_NOTEBOOK_PASSWORD'))")
    echo "c.NotebookApp.password = u'$HASH'" >> /usr/local/etc/jupyter/jupyter_notebook_config.py
fi

if [[ "$JUPYTERLAB" == true ]]; then
    echo "jupyter lab...."
    exec jupyter lab
else
    echo "jupyter notebook...."
    exec jupyter notebook
fi
